/**
 * Created by Igor on 16.11.2016.
 */
const ADD_NOTE = 'ADD_NOTE',
      FETCHING_NOTES = 'FETCHING_NOTES',
      FETCHED_NOTES = 'FETCHED_NOTES',
      TOGGLE_NOTE = 'TOGGLE_NOTE',
      DELETE_NOTE = 'DELETE_NOTE';

export {ADD_NOTE, FETCHING_NOTES, FETCHED_NOTES, TOGGLE_NOTE, DELETE_NOTE};
